# Generated by Django 5.2.6 on 2026-09-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Pin this title to the homepage spotlight. Leave off and the spotlight ranks titles by how many people bookmarked them recently.'),
        ),
    ]
