# Generated by Django 5.2.6 on 2026-09-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_alter_anime_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='anilist_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='The AniList entry this title is. Set by the catalogue seeder and by `train_recommender`, and used to tell a recommendation that we carry from one we do not.', null=True, unique=True),
        ),
    ]
